src/FELTP.Web/Controllers/ResidentManagementController.cs
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

using Application.ProgramManagement.Commands;
using Application.ProgramManagement.Queries;
using Application.ResidentManagement.Commands;
using Application.ResidentManagement.Queries;
using ProgramManagement.Domain.Program;
using Microsoft.AspNetCore.Authorization;
using FELTP.Web.Services;
using ResidentManagement.Domain;
using Newtonsoft.Json;
using UserManagement.Services.Authorization;
using Application.Common.Models;
using Application.Common.Models.Queries;

namespace FELTP.Web.Controllers
{
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [Authorize]
    public class ResidentManagementController : Controller
    {
        IMediator mediator;
        ISelectListLoader programSelectListLoader;
        IEnumerable<ISelectListLoader> selectListLoaders;
        public ResidentManagementController(IMediator _mediator, IEnumerable<ISelectListLoader> _selectListLoaders)
        {
            mediator = _mediator;
            selectListLoaders = _selectListLoaders;
            programSelectListLoader = selectListLoaders.Where(x => x.CanLoad(SelectItemType.Program)).SingleOrDefault();
        }

        public IActionResult DashBoard()
        {
            return View();
        }

        [Operation("Register New Applicant")]
        public async Task<IActionResult> RegisterNewApplicant(int Id)
        {
            var offerDetail = await mediator.Send(new GetProgramOfferById { OfferId = Id });

            var response = offerDetail.ValidateProgramOfferApplicationDuration();
            if (true)
            {
                var applicantCommand = new RegisterNewApplicantCommand()
                {
                    OfferName = offerDetail.Name,
                    ProgramName = offerDetail.ProgramName,
                    ProgramOfferId = offerDetail.Id
                };
                return View(applicantCommand);
            }

        }

        [HttpPost]
        [Operation("Register New Applicant")]
        public async Task<IActionResult> RegisterNewApplicant(RegisterNewApplicantCommand command, IFormFile statementFile)
        {
            if (!ModelState.IsValid)
                return View(command);

            if (command.PersonalStatementSubmitted)
            {
                if (statementFile == null)
                {
                    ModelState.AddModelError("StatementFile", "Please upload a personal statement file");
                    return View(command);
                }

                using (var memoryStream = new MemoryStream())
                {
                    statementFile.CopyTo(memoryStream);
                    command.File = new StatementFile(memoryStream.ToArray(), statementFile.ContentType,
                        statementFile.FileName);
                }
            }
            command.CreatedBy = User.Identity.Name;

            var applicantId = await mediator.Send(command, CancellationToken.None);

            if (applicantId == default(long))
                return View("Error");

            return RedirectToAction("ProgramOfferApplicants", "ProgramManagement", new { id = command.ProgramOfferId });
        }


        public async Task<IActionResult> ApplicantDetails(long applicantId, int offerId)
        {
            var applicantViewModel = await mediator.Send(new GetApplicantQuery { Id = applicantId, ProgramOfferId = offerId });
            applicantViewModel.IsApplicantPartial = true;

            return View(applicantViewModel);
        }

        [Operation("Edit Applicant Bio Data")]
        public async Task<IActionResult> _EditApplicantBioData(int applicantId, int programOfferId)
        {
            var applicant = await mediator.Send(new GetApplicantQuery() { Id = applicantId, ProgramOfferId = programOfferId });

            var updateApplicantCommand = new UpdateApplicantBioDataCommand
            {
                UpdatePersonBioData = new UpdatePersonBioDataCommand
                {
                    BioDataInfo = applicant.Person.BioDataInfo,
                    Cadres = await GetSelectListLoader(SelectItemType.Cadre).GetSelectListItemsAsync(null),
                },
                ApplicantId = applicantId,
                ProgramOfferId = programOfferId
            };

            return PartialView(updateApplicantCommand);
        }

        private ISelectListLoader GetSelectListLoader(SelectItemType selectItemType)
        {
            return selectListLoaders.Where(x => x.CanLoad(selectItemType)).SingleOrDefault();
        }

        [HttpPost]
        public async Task<IActionResult> _EditApplicantBioData(UpdateApplicantBioDataCommand command)
        {
            var id = await mediator.Send(command);

            return RedirectToAction(nameof(ApplicantDetails), new { applicantId = command.ApplicantId, offerId = command.ProgramOfferId });
        }

        [Operation("Edit Applicant Contact Info")]
        public async Task<IActionResult> _EditApplicantContactInfo(long personId, int applicantId, int programOfferId)
        {

            var person = await mediator.Send(new GetPersonQuery() { PersonId = personId });

            var model = new UpdatePersonContactInfoCommand
            {
                ContactInfo = person.ContactInfo,
                AddressInfo = person.AddressInfo,
                Countries = await GetSelectListLoader(SelectItemType.Country).GetSelectListItemsAsync(null),
                Counties = await GetSelectListLoader(SelectItemType.County).GetSelectListItemsAsync(person.AddressInfo.CountryId),
                Subcounties = await GetSelectListLoader(SelectItemType.Subcounty).GetSelectListItemsAsync(person.AddressInfo.CountyId),
                PersonId = personId,
                CorrelationId = applicantId,
                ProgramOfferId = programOfferId
            };

            return PartialView(model);
        }


        [HttpPost]
        public async Task<IActionResult> _EditApplicantContactInfo(UpdatePersonContactInfoCommand command)
        {
            var id = await mediator.Send(command);

            return RedirectToAction(nameof(ApplicantDetails), new { applicantId = command.CorrelationId, offerId = command.ProgramOfferId });

        }

        public IActionResult ApplicantTransition(int id)
        {
            return PartialView(new AddResidentCommand { ApplicantId = id });
        }

        [HttpPost]
        public async Task<IActionResult> ApplicantTransition(AddResidentCommand model)
        {
            model.CreatedBy = User.Identity.Name;
            var residentId = await mediator.Send(model);
            if (residentId == default(long))
                return View();

            return RedirectToAction(nameof(ResidentDetails), new { applicantId = model.ApplicantId });
        }

        [Operation("View Applicants List")]
        public async Task<IActionResult> ApplicantList()
        {
            var model = new FilterResident()
            {
                ProgramSelectList = await programSelectListLoader.GetSelectListAsync(null)
            };
            return View(model);
        }


        [HttpPost]
        [Operation("View Applicants List")]
        public async Task<IActionResult> GetApplicants(IDataTablesRequest request, int? Id, GetBy getBy)
        {
            var applicants = await mediator.Send(new GetApplicantListQuery() { GetApplicantBy = getBy, Id = Id });

            var filteredData = String.IsNullOrWhiteSpace(request.Search.Value)
                ? applicants
                : applicants.Where(_item => _item.IdentificationNumber.Contains(request.Search.Value));

            var dataPage = filteredData.Skip(request.Start).Take(request.Length);
            var response = DataTablesResponse.Create(request, applicants.Count(), filteredData.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }

        [Operation("View Applicants List")]
        public async Task<IActionResult> ResidentList()
        {
            var model = new FilterResident()
            {
                ProgramSelectList = await programSelectListLoader.GetSelectListAsync(null)

            };

            return View(model);
        }

        [HttpPost]
        [Operation("View Applicants List")]
        public async Task<IActionResult> GetResidents(IDataTablesRequest request, int? Id, GetBy getBy)
        {
            var residents = await mediator.Send(new GetResidentListQuery() { Id = Id, GetResidentBy = getBy });

            var filteredData = String.IsNullOrWhiteSpace(request.Search.Value)
                ? residents
                : residents.Where(_item => _item.IdentificationNumber.Contains(request.Search.Value));

            var dataPage = filteredData.Skip(request.Start).Take(request.Length);
            var response = DataTablesResponse.Create(request, residents.Count(), filteredData.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }


        public async Task<IActionResult> ResidentDetails(long applicantId, int offerId)
        {
            var resident = await mediator.Send(new GetApplicantQuery { Id = applicantId, ProgramOfferId = offerId });

            return View(resident);

        }

        [Operation("Enroll Resident")]
        public async Task<IActionResult> EnrollResident(long Id, long residentId, int offerId)
        {
            var offerDetails = await mediator.Send(new GetProgramOfferApplicationByApplicantId
            {
                ApplicantId = Id
            });
            string message = String.Empty;

            var programOfferPendingEnrollment = offerDetails

src/FELTP.Web/Views/ResidentManagement/AddResidentCourseAttendance.cshtml
@model AddResidentCourseAttendanceCommand

@{
    ViewData["Title"] = "Resident Course Attendance";
}

@section Scripts{
    <script src="~/js/feltp/program-dropdown.js"></script>
    <script src="~/js/feltp/program-offer-resident.js"></script>
}

  <section class="content">
        <div class="row">
            <div class="col-md-12">
                <section class="content-header">
                    <ol class="breadcrumb pull-right">
                        <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                        <li><a href="#"><u>Course Attendance</u></a></li>
                    </ol>
                </section>
                <h1 class="page-head-line">Mark Course Attendance</h1>
            </div>
        </div>
        <div class="box box-header">
            <div class="box-body">
                <form method="post" asp-action="AddResidentCourseAttendance" asp-controller="ResidentManagement" id="resident-attendance-frm">
                    @Html.Hidden("Status")
                    <div class="row" style="padding-bottom: 30px;">
                        <div class="form-group">

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Select Program</label>
                                    <select asp-for="ProgramId" asp-items="@Model.Programs" data-live-search="true"
                                            class="form-control selectpicker">
                                        <option selected="selected" value="0">Select Program</option>
                                    </select>
                                    <span asp-validation-for="ProgramId" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <label class="control-label">Select Program Offer</label>
                                    <select asp-for="ProgramOfferId" class="form-control selectpicker" data-live-search="true">
                                        <option value="0">Select Offer</option>
                                    </select>
                                    <span asp-validation-for="ProgramOfferId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Select Semester Schedule</label>
                                    <select asp-for="SemesterScheduleId" class="form-control selectpicker"
                                            asp-items="Model.SemeseterScheduleSelectList"
                                            data-live-search="true">
                                        <option value="0">Select</option>
                                    </select>
                                    <span asp-validation-for="SemesterScheduleId" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <label class="control-label">Select Course Schedule</label>
                                    <select asp-for="CourseScheduleId" class="form-control selectpicker"
                                            data-live-search="true">
                                        <option value="0">Select</option>
                                    </select>
                                    <span asp-validation-for="CourseScheduleId" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Select Topic</label>
                                    <select asp-for="UnitId" class="form-control selectpicker" data-live-search="true">
                                        <option value="0">Select Topic</option>
                                    </select>
                                    <span asp-validation-for="UnitId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Select Attendance Date</label>
                                    <select asp-for="StrAttendanceDate" data-live-search="true" class="form-control selectpicker">
                                        <option value="0">Select Date</option>
                                    </select>
                                    <span asp-validation-for="StrAttendanceDate" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Select Faculty</label>
                                    <select asp-for="StrFacultyTimetableItem" class="form-control selectpicker"></select>
                                    <span asp-validation-for="StrFacultyTimetableItem" class="text-danger"></span>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div id="residents-div" style="display:none" class="residents">
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <table id="enrolled-residents-table" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="box-footer">
                        <div class="form-group">
                            <a asp-action="Dashboard">Back to Home</a>
                            <input type="submit" value="Submit" class="btn btn-primary pull-right" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>

<style>
    .marked {
        background-color: grey;
   }
</style>

src/FELTP.Web/Views/ResidentManagement/ApplicantDetails.cshtml
@model ApplicantViewModel

@{
    ViewData["Title"] = "Applicant Details";
}

@{
    Html.RenderPartial("_Details", Model);
}


@section Scripts
    {
    <script src="~/js/feltp/program-offer-applicants-list.js"></script>
    <script src="~/js/feltp/applicant-resident-common-grids.js"></script>
    <script src="~/js/feltp/program-dropdown.js"></script>
    <script src="~/js/feltp/resident-management.js"></script>
    <script src="~/js/feltp/county-dropdown.js"></script>
    <script src="~/js/feltp/subcounty-dropdown.js"></script>
}

src/FELTP.Web/Views/ResidentManagement/ApplicantEvaluationDetails.cshtml
@model ApplicantEvaluationViewModel


<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title"> @Model.ProgramOfferApplicationDetail.Name - Program Application Details </h4>
        </div>
        <form asp-action="ApplicantEvaluation">
            @Html.Hidden("Id", Model.ProgramOfferApplicationDetail.Id)
            @Html.Hidden("ApplicantId", Model.ProgramOfferApplicationDetail.ApplicantId)
            <div class="modal-body">
                <div class="col-md-6">
                    <b> Program</b>
                </div>
                <div class="col-md-6" style="margin-bottom:10px">
                    @Html.DisplayFor(model => model.ProgramOfferApplicationDetail.Program)
                </div>

                <div class="col-md-6">
                    <b>Program Offer Name</b>
                </div>
                <div class="col-md-6" style="margin-bottom:10px">
                    @Html.DisplayFor(model => model.ProgramOfferApplicationDetail.ProgramOfferName)
                </div>
                <div class="col-md-6">
                    <b>Application Status</b>
                </div>
                <div class="col-md-6" style="margin-bottom:10px">
                    @Html.DisplayFor(model => model.ProgramOfferApplicationDetail.StrApplicationStatus)
                </div>
                <div class="col-md-6">
                    <b>Date Applied</b>
                </div>
                <div class="col-md-6" style="margin-bottom:10px">
                    @Html.DisplayFor(model => model.ProgramOfferApplicationDetail.DateApplied)
                </div>
                <div class="col-md-6">
                    <b> Approved By County </b>
                </div>
                <div class="col-md-6" style="margin-bottom:10px">
                    @Model.ProgramOfferApplicationDetail.ApprovedByCounty

                </div>
                @if (Model.InterviewScore != null)
                {

                    <div class="col-md-6">
                        <b>Oral Interview Score</b>
                    </div>

                    <div class="col-md-6" style="margin-bottom:10px">
                        @Html.DisplayFor(model => model.InterviewScore.OralInterview)
                    </div>

                    <div class="col-md-6">
                        <b>Written Interview Score</b>
                    </div>

                    <div class="col-md-6" style="margin-bottom:10px">
                        @Model.InterviewScore.WrittenInterview
                    </div>


                    <div class="col-md-6">
                        <b>Average Interview Score</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        @{
                            var average = Math.Floor((double)Model.InterviewScore.Total / 2);

                        }
                        @average
                    </div>
                }


                @if (Model.ProgramOfferApplicationDetail.DateEvaluated != null)
                {
                    <div class="col-md-6">
                        <b>Evaluated By</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        @Html.DisplayFor(model => model.ProgramOfferApplicationDetail.EvaluatedBy)
                    </div>
                    <div class="col-md-6">
                        <b>Date Evaluated</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        @Model.ProgramOfferApplicationDetail.DateEvaluated
                    </div>
                    <div class="col-md-6">
                        <b>Comment</b>
                    </div>

                    <div class="col-md-6" style="margin-bottom:10px">
                        @Html.DisplayFor(x => x.ProgramOfferApplicationDetail.Comment)
                    </div>

                }



                @if (Model.ProgramOfferApplicationDetail.PersonalStatementSubmitted)
                {

                    <a asp-controller="ResidentManagement" asp-action="DownloadStatementFile" asp-route-id="@Model.ProgramOfferApplicationDetail.Id">
                        Download Personal Statement File
                    </a>
                }

            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

src/FELTP.Web/Views/ResidentManagement/ApplicantTransition.cshtml
@model AddResidentCommand

@using (Html.BeginForm("ApplicantTransition", "ResidentManagement", FormMethod.Post, 
     new { id = "myForm", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model=>model.ApplicantId)

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Transition Applicant</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <h4>Are you sure you want to transition this applicant to a resident</h4>
                </div>

            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-primary" value="Transition" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/FELTP.Web/Views/ResidentManagement/CadreList.cshtml
@{
    ViewData["Title"] = "Cadre List";
}

@section Scripts
    {
    <script type="text/javascript" src="~/js/feltp/resident-management.js"></script>
}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <section class="content-header">
                <ol class="breadcrumb pull-right">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="#">Cadre List</a></li>
                </ol>
            </section>
            <h1 class="page-head-line">
                @ViewData["Title"]
            </h1>
        </div>
    </div>
    <div class="box box-header">
        <div class="box-body">
            <button type="button" class="btn btn-default btn-md" style="margin-bottom:10px" data-toggle="modal" data-url="@Url.Action("_AddCadre","ResidentManagement")" id="btnCreateCadre">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create New
            </button>
            <table id="cadre-list" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>
        </div>
    </div>
</section>
<div class="modal fade" id="createCadreModal" tabindex="-1" role="dialog" aria-labelledby="CreateCadreModal" aria-hidden="true" data-backdrop="static">
    <div id="createCadreContainer">
    </div>
</div>

<div class="modal fade" id="editCadreModal" tabindex="-1" role="dialog" aria-labelledby="EditCadreModal" aria-hidden="true" data-backdrop="static">
    <div id="editCadreContainer">
    </div>
</div>
<div class="modal fade" id="detailsCadreModal" tabindex="-1" role="dialog" aria-labelledby="DetailsCadreModal" aria-hidden="true" data-backdrop="static">
    <div id="detailsCadreContainer">
    </div>
</div>

<div class="modal fade" id="deactivateCadreModal" tabindex="-1" role="dialog" aria-labelledby="DeactivateCadreModal" aria-hidden="true" data-backdrop="static">
    <div id="deactivateCadreContainer">
    </div>
</div>

src/FELTP.Web/Views/ResidentManagement/EnrollResidentResult.cshtml
@model ResidentEnrollmentResult
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Applicant Enrollment Result</h4>
        </div>

        <div class="modal-body">
            @{
                var alertType = Model.Successful ? "alert-success" : "alert-danger";
            }
            <div class="alert @alertType">
                @Model.Message
            </div>
        </div>
        <div class="modal-footer">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="button" class="btn btn-default" 
                            data-url="@Url.Action("ResidentDetails","ResidentManagement",new { applicantId = Model.ApplicantId, offerId = Model.ProgramOfferId })"
                            data-dismiss="modal" onclick="javascript:window.location.reload()">
                        Close
                    </button>
                </div>
            </div>
        </div>

    </div>
</div>

src/FELTP.Web/Views/ResidentManagement/EnrolledResidentsList.cshtml
<script src="~/js/feltp/resident-attendance-list.js"></script>
<div>
    <table id="residents-list-table" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>
</div>

src/FELTP.Web/Views/ResidentManagement/ResidentCourseAttendance.cshtml
@model ResidentUnitAttendanceViewModel

<div class="modal-dialog" style="width:1100px">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">@Model.Course Attendance Details </h4>
        </div>
         @Html.Hidden("ResidentCourseWorkId_AttendanceList", Model.ResidentCourseWorkId)
        <div class="modal-body">
            <table id="residents-course-attendance" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>
        </div>
    </div>
</div>

src/FELTP.Web/Views/ResidentManagement/ResidentUnitsList.cshtml
@model ResidentUnitViewModel

<div class="modal-dialog" style="width:900px">
    @Html.Hidden("ResidentCourseWorkId_UnitList",Model.ResidentCourseWorkId)
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">@Model.Course - Units</h4>
        </div>
        <div class="modal-body">
            <table id="resident-module-list" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>

        </div>
    </div>
</div>

src/FELTP.Web/Views/ResidentManagement/SearchApplicantResult.cshtml
@model SearchApplicantQuery
@{
    ViewData["Title"] = "Applicant Search Results";
}


@section Scripts
    {
    <script type="text/javascript" src="~/js/feltp/applicants-list.js"></script>
}

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <section class="content-header">
                <ol class="breadcrumb pull-right">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="/ResidentManagement/Dashboard"><i class="fa fa-dashboard"></i> Resident Dashboard</a></li>
                    <li><a href="/ResidentManagement/SearchApplicant?Id=@Model.OfferId"><i class="fa fa-search"></i>Search </a></li>
                    <li><a href="#"><u>Search Result</u></a></li>
                </ol>
            </section>
            <h1 class="page-head-line"> Applicant Search Result </h1>
        </div>
    </div>
    <div class="box box-header">
        @Html.HiddenFor(x => x.IdentificationNumber)
        <div class="box-body">
            <table id="applicants-search-list-table" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>            
        </div>
        <div class="pull-left">
            <a asp-controller="ResidentManagement" asp-action="SearchApplicant" asp-route-Id="@Model.OfferId">Back to Search</a>
        </div>
    </div>
</section>

src/FELTP.Web/Views/ResidentManagement/_AddCadre.cshtml
@model Application.ResidentManagement.Commands.AddCadreCommand

@{
    ViewData["Title"] = "Add Cadre";
}

@using (Html.BeginForm("_AddCadre", "ResidentManagement", FormMethod.Post, new { id = "myForm", enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Add Cadre</h4>
            </div>

            <div class="modal-body">
                <form asp-action="_AddCadre" asp-antiforgery="true">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn bg-purple" value="Save" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
@section Scripts
    {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}