src/FELTP.Web/Controllers/SemesterManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application;
using Application.Common.Services;
using Application.FacultyManagement.Queries;
using Application.ProgramManagement.Commands;
using Application.ProgramManagement.Queries;
using Application.ProgramManagement.QueryHandlers;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using FELTP.Web.Services;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProgramManagement.Domain.Program;
using UserManagement.Services.Authorization;

namespace FELTP.Web.Controllers
{
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [Authorize]
    public class SemesterManagementController : Controller
    {
        IMediator mediator;
        ISelectListLoader programSelectListLoader;
        IEnumerable<ISelectListLoader> selectListLoaders;

        public SemesterManagementController(IMediator _mediator, IEnumerable<ISelectListLoader> _selectListLoaders)
        {
            mediator = _mediator;
            selectListLoaders = _selectListLoaders;
            programSelectListLoader = selectListLoaders.FirstOrDefault(x => x.CanLoad(SelectItemType.Program));
        }

        [Operation("Add Semester")]
        public IActionResult _AddSemester()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Operation("Add Semester")]
        public async Task<ActionResult> _AddSemester(AddSemesterCommand addSemester)
        {
            if (!ModelState.IsValid)
            {
                return View(addSemester);
            }

            int semesterId = await mediator.Send(addSemester);
            return RedirectToAction(nameof(SemesterList));
        }

        [Operation("Edit Semester")]
        public async Task<IActionResult> _EditSemester(int id)
        {
            var semester = await mediator.Send(new GetSemesterList() {Id = id});

            return PartialView(semester.FirstOrDefault());
        }

        [HttpPost]
        [Operation("Edit Semester")]
        public async Task<IActionResult> _EditSemester(UpdateSemesterCommand command)
        {
            var id = await mediator.Send(command);

            return PartialView("EditSemesterResult", "Semester details updated succesfully");
        }

        [Operation("View Semester Details")]
        public async Task<IActionResult> _DetailsSemester(int id)
        {
            var semester = await mediator.Send(new GetSemesterList() {Id = id});

            return PartialView(semester.FirstOrDefault());
        }


        [Operation("View Semester List")]
        public IActionResult SemesterList()
        {
            return View();
        }

        [HttpPost]
        [Operation("View Semester List")]
        public async Task<IActionResult> GetSemesters(IDataTablesRequest request)
        {
            var semesters = await mediator.Send(new GetSemesterList());

            var filteredData = String.IsNullOrWhiteSpace(request.Search.Value)
                ? semesters
                : semesters.Where(_item => _item.Name.Contains(request.Search.Value));

            var dataPage = filteredData.Skip(request.Start).Take(request.Length);
            var response = DataTablesResponse.Create(request, semesters.Count(), filteredData.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }

        public async Task<JsonResult> GetSemesters()
        {
            var programTiers = await mediator.Send(new GetSemesterList());
            var tiers = programTiers.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            }).ToList();

            return Json(tiers);
        }

        [Operation("Deactivate Semester")]
        public ActionResult _DeactivateSemester(int id)
        {
            return PartialView("_DeactivateSemester");
        }

        [HttpPost]
        [Operation("Deactivate Semester")]
        public async Task<IActionResult> _DeactivateSemester(DeactivateSemesterCommand command)
        {
            if (!ModelState.IsValid)
            {
                command = await SetDeactivateSemesterCommandModel(command.Id);
                return View(command);
            }

            command.DeactivatedBy = User.Identity.Name;

            var id = await mediator.Send(command);

            return RedirectToAction(nameof(SemesterList));
        }

        private async Task<DeactivateSemesterCommand> SetDeactivateSemesterCommandModel(int semesterId)
        {
            var deactivateSemesterCommand = new DeactivateSemesterCommand();

            var semesterList = await mediator.Send(new GetSemesterList {Id = semesterId});

            var semester = semesterList.SingleOrDefault();

            return deactivateSemesterCommand;
        }

        public async Task<IActionResult> CreateSemesterSchedule()
        {
            var model = new AddSemesterScheduleCommand
            {
                ProgramSelectList = await programSelectListLoader.GetSelectListAsync(null)
            };

            return View(model);
        }

        [HttpPost]
        [Operation("Add Semester Schedule")]
        public async Task<IActionResult> CreateSemesterSchedule(AddSemesterScheduleCommand model)
        {
            if (!ModelState.IsValid)
            {
                model.ProgramSelectList = await programSelectListLoader.GetSelectListAsync(null);
                return View(model);
            }

            model.CreatedBy = User.Identity.Name;

            var result = await mediator.Send(model);

            if (result.CreatedSuccesfully)
                return RedirectToAction(nameof(SemesterScheduleList));

            ModelState.AddModelError("Response", result.Message);

            return View(model);
        }

        [Operation("View Semester Schedule")]
        public IActionResult SemesterScheduleList()
        {
            return View();
        }

        [Operation("View Semester Schedule")]
        public async Task<IActionResult> GetSemesterScheduleList(IDataTablesRequest request)
        {
            var scheduleList = await mediator.Send(new GetSemesterScheduleList { });

            var filteredData = String.IsNullOrWhiteSpace(request.Search.Value)
                ? scheduleList
                : scheduleList.Where(_item => _item.Description.Contains(request.Search.Value));

            var dataPage = filteredData.Skip(request.Start).Take(request.Length);
            var response = DataTablesResponse.Create(request, scheduleList.Count(), filteredData.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }

        public async Task<IActionResult> GetSemesterScheduleItemList(IDataTablesRequest request, int semesterScheduleId)
        {
            var scheduleList = await mediator.Send(new GetSemesterScheduleItemList
            {
                SemesterScheduleId = semesterScheduleId
            });

            var filteredData = String.IsNullOrWhiteSpace(request.Search.Value)
                ? scheduleList
                : scheduleList.Where(_item => _item.Name.Contains(request.Search.Value));

            var dataPage = filteredData.Skip(request.Start).Take(request.Length);
            var response = DataTablesResponse.Create(request, scheduleList.Count(), filteredData.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }


        [Operation("View Semester Schedule Details")]
        public async Task<IActionResult> SemesterScheduleDetails(int id)
        {
            var scheduleList = await mediator.Send(new GetSemesterScheduleList {Id = id});

            return View(scheduleList.SingleOrDefault());
        }

        [Operation("Add Unit")]
        public async Task<IActionResult> AddExaminationSchedule(int scheduleId, int programId, int semesterId)
        {
            var model = new AddSemesterScheduleItemCommand()
            {
                ProgramCourses = await GetProgramCourses(programId, semesterId, ScheduleItemType.Examination),
                ScheduleItemType = ScheduleItemType.Examination,
                SemesterScheduleId = scheduleId,
                ProgramId = programId,
                SemesterId = semesterId,
                SemesterSchedule = await GetSemesterSchedule(scheduleId),
            };

            return PartialView(model);
        }

        public async Task<IActionResult> CompleteSemesterRequest(int semesterScheduleId)
        {
            var semesterScheduleDetails = await mediator.Send(new GetSemesterScheduleList {Id = semesterScheduleId});

            var semesterSchedule = semesterScheduleDetails.SingleOrDefault();

            var completeSemesterModel = new CompleteSemesterCommand()
            {
                ScheduleName = semesterSchedule.Description,
                StartDate = semesterSchedule.EstimatedStartDate,
                EndDate = semesterSchedule.EstimatedEndDate,
                SemesterScheduleId = semesterScheduleId
            };

            return PartialView(completeSemesterModel);
        }

        [HttpPost]
        public async Task<IActionResult> CompleteSemesterRequest(CompleteSemesterCommand model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(model);
            }

            model.RequestedBy = User.Identity.Name;
            model.DateRequested = DateTime.Now;
            var result = await mediator.Send(model);

            if (result.CreatedSuccesfully)
                return PartialView("ScheduleResult", result);

            ModelState.AddModelError("Response", result.Message);
            return PartialView(model);
        }

src/FELTP.Web/Views/SemesterManagement/AddCourseSchedule.cshtml
@model AddSemesterScheduleItemCommand

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Create @Model.SemesterSchedule.Semester Course Schedule</h4>
        </div>
        <form id="create-course-schedule-form" action="/SemesterManagement/AddCourseSchedule">
            <div class="modal-body" id="course-schedule-div">
                <div asp-validation-summary="All" class="text-danger"></div>
                @Html.HiddenFor(x => x.SemesterScheduleId)
                @Html.HiddenFor(x => x.SemesterId)
                @Html.HiddenFor(x => x.ProgramId)
                @Html.HiddenFor(x => x.ScheduleItemType)
                @Html.Hidden("SemesterStartDate", Model.SemesterSchedule.StartDate)
                @Html.Hidden("SemesterEndDate", Model.SemesterSchedule.EndDate)

                <div class="form-group">
                        <label class="control-label"> Semester Start Date </label>
                        <input type="text" asp-for="SemesterSchedule.StartDate" class="form-control" disabled="disabled" />
                        </div>
                <div class="form-group">
                        <label class="control-label"> Semester End Date  </label> <br />
                        <input type="text" asp-for="SemesterSchedule.EndDate" class="form-control" disabled="disabled" />
                </div>
                    <div class="form-group">
                        <label class="control-label">Select Course Title</label>
                        <select asp-for="ProgramCourseId" asp-items="@Model.ProgramCourses"
                                class="form-control selectpicker" data-live-search="true">
                            <option value="0">Select Course</option>
                        </select>
                        <span asp-validation-for="ProgramCourseId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Start Date</label>
                        <div class='input-group date' id='StrStartDate'>
                            <input type='text' asp-for="StrStartDate" class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label"> Duration In Weeks </label>
                        <input type="text" asp-for="Duration" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label class="control-label"> End Date </label>
                        <input type="text" asp-for="StrEndDate" class="form-control" />
                    </div>

                    <script type="text/javascript">
                        $(function () {
                            var semStartDate = $("#SemesterStartDate").val();
                            var semEndDate = $("#SemesterEndDate").val();
                            console.log(semStartDate);
                            console.log(semEndDate);
                            
                            $('#StrStartDate').datetimepicker({
                                format: 'DD/MM/YYYY',
                                useCurrent: false,
                            });
                            
                            $('#StrStartDate').data("DateTimePicker").minDate(semStartDate);
                            $('#StrStartDate').data("DateTimePicker").maxDate(semEndDate);                                                   
                        });
                    </script>
                </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="button" id="create-course-schedule-btn" value="Save" class="btn bg-purple"/>
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
@section Scripts {


    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/FELTP.Web/Views/SemesterManagement/AdjustSemesterSchedule.cshtml
@model InitiateSemesterScheduleChangeRequest
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Semester Schedule Date Adjustment</h4>
        </div>
        <form action="/SemesterManagement/AdjustSemesterSchedule" method="post" id="edit-semester-schedule-form">
            <div asp-validation-summary="All" class="text-danger">
            </div>
            <div class="modal-body">
                @Html.HiddenFor(x => x.SemesterScheduleId)
                @Html.HiddenFor(x => x.ProgramOfferId)
                @Html.HiddenFor(x => x.OfferStartDate)
                @Html.HiddenFor(x => x.OfferEndDate)
                @Html.HiddenFor(x => x.Duration)
                @Html.HiddenFor(x => x.ProgramOffer)
                @Html.HiddenFor(x => x.ScheduleName)
                @Html.HiddenFor(x => x.Status)
                @Html.HiddenFor(x=>x.Semester)

                <div class="row">
                    <div class="col-md-6">
                        <b> Program Offer</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        @Model.ProgramOffer
                    </div>
                    <div class="col-md-6">
                        <b> Schedule Name</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        @Model.ScheduleName
                    </div>
                    <div class="col-md-6">
                        <b> Semester</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        @Model.Semester
                    </div>
                    <div class="col-md-6">
                        <b> Start Date</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        <div class='input-group date' id='StrStartDate'>
                            <input type='text' asp-for="StartDate" class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <b> End Date</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        <div class='input-group date' id='StrEndDate'>
                            <input type='text' asp-for="EndDate" class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>


                    <div class="col-md-6">
                        <b> Semester Duration</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        @Model.Duration Weeks
                    </div>
                    <script>
                        $(function () {

                            var offerStartDate = $("#OfferStartDate").val();
                            var offerEndDate = $("#OfferEndDate").val();

                            $('#StrStartDate').datetimepicker({
                                format: 'DD/MM/YYYY'
                            });

                            $('#StrEndDate').datetimepicker({
                                format: 'DD/MM/YYYY'
                            });

                            $('#StrStartDate').data("DateTimePicker").minDate(offerStartDate);
                            $('#StrStartDate').data("DateTimePicker").maxDate(offerEndDate);
                            $('#StrEndDate').data("DateTimePicker").minDate(offerStartDate);
                            //$('#StrEndDate').data("DateTimePicker").maxDate(offerEndDate);

                        });
                    </script>
                    <div class="col-md-6">
                        <b> Comment</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        <input type='text' asp-for="Comment" class="form-control" />
                    </div>
                </div>
            </div>
        </form>

        <div class="modal-footer">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" id="btn-update-semester-details" class="btn bg-purple" value="Save" />
                </div>
            </div>
        </div>


    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/FELTP.Web/Views/SemesterManagement/AdjustSemesterScheduleResponse.cshtml
@model SemesterScheduleChangeResponse
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Semester Schedule Result</h4>
        </div>

        <div class="modal-body">
            <text class="success">
                @Model.Message
            </text>
        </div>
        <div class="modal-footer">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="button" class="btn btn-default"
                            data-url="@Url.Action("SemesterScheduleDetails","SemesterManagement",new { Id = Model.SemesterScheduleId })" data-dismiss="modal" onclick="javascript:window.location.reload()">
                        Close
                    </button>
                </div>
            </div>
        </div>

    </div>
</div>

src/FELTP.Web/Views/SemesterManagement/SemesterScheduleChangeRequests.cshtml
@{
    ViewData["Title"] = "Semester Schedule Change Requests";
}

@section Scripts
 {
    <script type="text/javascript" src="~/js/feltp/semester-management.js"></script>
}

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <section class="content-header">
                <ol class="breadcrumb pull-right">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="/SemesterManagement/SemesterScheduleChangeRequests">Schedule Change Request</a></li>
                </ol>
            </section>
            <h1 class="page-head-line">Semester Schedule Change Requests</h1>
        </div>
    </div>
    <div class="box box-header">
        <div class="box-body">
            <table id="semester-schedule-change-request" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>
        </div>
    </div>
</section>

<div class="modal fade" id="approve-schedule-change-modal" tabindex="-1" role="dialog" aria-labelledby="Approve Semester Schedule Change" aria-hidden="true" data-backdrop="static">
    <div id="approve-schedule-change-container">
    </div>
</div>

src/FELTP.Web/Views/SemesterManagement/SemesterScheduleList.cshtml
@{
    ViewData["Title"] = "Semester Schedule List";
}


@section Scripts
{
    <script type="text/javascript" src="~/js/feltp/semester-management.js"></script>
}

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <section class="content-header">
                <ol class="breadcrumb pull-right">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="#"><U>SemesterSchedule</U></a></li>
                </ol>
            </section>
            <h1 class="page-head-line">Semester Schedule List </h1>
        </div>
    </div>
    <div class="box box-header">
        <div class="box-body">
            <a asp-controller="SemesterManagement" asp-action="CreateSemesterSchedule" class="btn btn-default btn-md" style="margin-bottom:10px"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>  Create New</a><p></p>
            <table id="semester-schedule-list-table" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>
        </div>
    </div>
</section>

src/FELTP.Web/Views/SemesterManagement/ViewCourseTimetable.cshtml
@model TimetableViewModel
@{
    var split = Model.ScheduleItemName.Split("(");

    ViewData["Title"] = $" { split[0] } Course Timetable";
}

@section Scripts
  {
    <script type="text/javascript" src="~/js/feltp/semester-management.js"></script>
  }
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <section class="content-header">
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="#">View Course Timetable</a></li>
                </ol>
            </section>
            <h1 class="page-head-line">@ViewData["Title"]</h1>
        </div>
    </div>
    <div class="box box-header">
        <div class="box-body">
            @Html.HiddenFor(x => x.SemesterScheduleItemId)
            <table id="course-timetable-schedule-table" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>
        </div>
        <div class="box-footer">
            <a asp-controller="SemesterManagement" asp-action="SemesterScheduleDetails" asp-route-Id="@Model.SemesterScheduleId">Back to Details</a>
        </div>
    </div>
</section>

<div class="modal fade" id="editCourseTimetableModal" tabindex="-1" role="dialog" aria-labelledby="Edit Course Timetable" aria-hidden="true" data-backdrop="static">
    <div id="editCourseTimetablecontainer">
    </div>
</div>
<div class="modal fade" id="viewCourseTimetablemodal" tabindex="-1" role="dialog" aria-labelledby="View Course Timetable" aria-hidden="true" data-backdrop="static">
    <div id="viewCourseTimetableontainer">
    </div>
</div>

src/FELTP.Web/Views/SemesterManagement/_AddSemester.cshtml
@model AddSemesterCommand

@{
    ViewData["Title"] = "Add Semeter";
}

@using (Html.BeginForm("_AddSemester", "SemesterManagement", FormMethod.Post, new { id = "myForm", enctype = "multipart/form-data" }))
{
@Html.ValidationSummary(true)
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Add Semeter</h4>
        </div>

        <div class="modal-body">
            <form asp-action="AddFacultyRole" asp-antiforgery="true">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn bg-purple" value="Save" />
                </div>
            </div>
        </div>


    </div>
</div>
}
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
@section Scripts
 {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/FELTP.Web/Views/SemesterManagement/_DeactivateSemester.cshtml
@model SemesterViewModel
@{
    Layout = null;
}

@using (Html.BeginForm("_DeactivateSemester", "SemesterManagement", FormMethod.Post, new { id = "myForm", enctype = "multipart/form-data" }))
{

<div class="modal-dialog" style="width: 400px;">
    <div class="modal-content">
        <div class="modal-header">
            <center>
                <h4 class="modal-title">
                    Deactivate Semester<button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </h4>
            </center>
            
        </div>
        <div class="modal-body">
            <center><i class="fa fa-warning danger" style="font-size:48px;color:#d9534f;"></i></center>
            <center><h5>Are you sure you want to deactivate this?</h5></center>
        </div>
        <div class="modal-footer">
            @Html.HiddenFor(x => x.Id)          
            @Html.ActionLink("Close", "SemesterList", null, new { data_dismiss = "modal" }, new { @class = "btn btn-default pull-left" })
            <input type="submit" value="Deactivate" class="btn btn-danger pull-right" />
        </div>
    </div>
</div>
}

src/FELTP.Web/Views/SemesterManagement/_DetailsSemester.cshtml
@model SemesterViewModel

    <div class="modal-dialog" style="width: 500px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Semester Details</h4>
            </div>

            <div class="modal-body">
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.CreatedBy)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.CreatedBy)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Status)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Status)
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md col-md-12">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>


        </div>
    </div>
}
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
@section Scripts {


    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/FELTP.Web/Views/SemesterManagement/_EditTimetableResult.cshtml
@model AddTimetableResponse
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Timetable Edit Result</h4>
        </div>

        <div class="modal-body">
            <text class="success">
                @Model.Message
            </text>
        </div>
        <div class="modal-footer">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="button" class="btn btn-default"
                            data-url="@Url.Action("SemesterScheduleDetails","SemesterManagement",new { Id = Model.SemesterScheduleId })" data-dismiss="modal" onclick="javascript:window.location.reload()">
                        Close
                    </button>
                </div>
            </div>
        </div>

    </div>
</div>