src/FELTP.Web/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.ProgramManagement.Commands;
using Application.ProgramManagement.Queries;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using FELTP.Web.Services;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UserManagement.Services.Authorization;

namespace FELTP.Web.Controllers
{
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [Authorize]
    public class UnitController : Controller
    {
        private readonly IMediator mediator;
        IEnumerable<ISelectListLoader> selectListLoaders;

        public UnitController(IMediator _mediator, IEnumerable<ISelectListLoader> _selectListLoaders)
        {
            mediator = _mediator;
            selectListLoaders = _selectListLoaders;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Operation("Add Unit")]
        public IActionResult AddUnit()
        {
            return View();
        }

        [HttpPost]
        [Operation("Add Unit")]
        public async Task<IActionResult> AddUnit(AddUnitCommand model)
        {
            if (!ModelState.IsValid)
                return View();

            model.CreatedBy = User.Identity.Name;
            var unitId = await mediator.Send(model);
            
            return RedirectToAction(nameof(UnitList));
        }

        public async Task<IActionResult> EditUnit(int Id)
        {
            var unit = await mediator.Send(new GetUnit { Id = Id });
            var editUnitModel = new UpdateUnitCommand
            {
                Id = unit.Id,
                Code = unit.Code,
                Name = unit.Name,
                Description = unit.Description,
                CreatedBy = unit.CreatedBy,
                HasFieldPlacementActivity = unit.HasActivity,
                FieldPlacementActivities = await GetSelectListLoader(SelectItemType.FieldPlacementActivity).GetSelectListItemsAsync(null),
                FieldPlacementActivityId = unit.FieldPlacementActivityIds
            };

            return PartialView(editUnitModel);
        }
        [HttpPost]
        public async Task<IActionResult> EditUnit(UpdateUnitCommand command)
        {
            if (!ModelState.IsValid)
                return PartialView(command);

            command.UpdatedBy = User.Identity.Name;
            var result = await mediator.Send(command);

           if(result.IsSuccessful)
            return PartialView("UnitResponse",result);

            ModelState.AddModelError("Response", result.Message);
            return PartialView(command);
        }

        [Operation("View Unit List")]
        public IActionResult UnitList()
        {
            return View();
        }

        [HttpPost]
        [Operation("View Unit List")]
        public async Task<IActionResult> GetUnits(IDataTablesRequest request)
        {
            var units = await mediator.Send(new GetUnitList());

            var filteredData = String.IsNullOrWhiteSpace(request.Search.Value)
                ? units
                : units.Where(_item => _item.Name.Contains(request.Search.Value));

            var dataPage = filteredData.Skip(request.Start).Take(request.Length);
            var response = DataTablesResponse.Create(request, units.Count(), filteredData.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }

        public async Task<JsonResult> GetUnits(bool hasActivity)
        {
            var units = await mediator.Send(new GetUnitList() { HasActivity = hasActivity, IsDropDownRequest = true });
            var unitsListItems = units.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            }).ToList();

            return Json(unitsListItems);
        }

        public async Task<JsonResult> GetUnitFieldPlacementActivityAndDeliverables(int unitId)
        {
            var result = await mediator.Send(new GetUnitFieldPlacementActivityWithDeliverables { UnitId = unitId });

            return Json(result);
        }

        [Operation("View Unit List")]
        public  async Task<IActionResult> ViewDetails(int Id)
        {
            var unit = await mediator.Send(new GetUnit { Id = Id });

            return PartialView(unit);
        }

        [Operation("View Unit List")]
        public async Task<IActionResult> ViewUnitActivities(int Id)
        {
            var unit = await mediator.Send(new GetUnit { Id = Id });

            return PartialView(unit);
        }


        [HttpPost]
        [Operation("View Unit List")]
        public async Task<IActionResult> GetUnitActivities(IDataTablesRequest request, int unitId)
        {
            var activities = await mediator.Send(new GetUnitFieldPlacementActivities { UnitId = unitId });

            var filteredData = String.IsNullOrWhiteSpace(request.Search.Value)
                ? activities
                : activities.Where(_item => _item.Name.Contains(request.Search.Value));

            var dataPage = filteredData.Skip(request.Start).Take(request.Length);
            var response = DataTablesResponse.Create(request, activities.Count(), filteredData.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }

        private ISelectListLoader GetSelectListLoader(SelectItemType selectItemType)
        {
            return selectListLoaders.SingleOrDefault(x => x.CanLoad(selectItemType));
        }

    }
}

src/FELTP.Web/Views/Unit/AddUnit.cshtml
@model AddUnitCommand

@{
    ViewData["Title"] = "Add Topic";
}
@section Scripts
 {
<script type="text/javascript" src="~/js/feltp/field-placement-activity-dropdown.js"></script>
 }

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <section class="content-header">
                    <ol class="breadcrumb pull-right">
                        <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                        <li><a href="/Unit/UnitList">Topic List</a></li>
                        <li><a href="#">Add Topic</a></li>
                    </ol>
                </section>
                <h1 class="page-head-line">Add Topic</h1>
            </div>
        </div>
        <div class="box box-header">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                        <form asp-action="AddUnit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Code" class="control-label"></label>
                                <input asp-for="Code" class="form-control" />
                                <span asp-validation-for="Code" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label class="control-label" style="display:inline">Has Activity</label>
                                <input class="checkbox" type="checkbox" asp-for="HasFieldPlacementActivity" />
                            </div>
                            <div class="form-group" id="field-placement-activity-div" style="display:none">
                                <label class="control-label">Field Placement Activity</label>
                                <select class="form-control selectpicker" multiple asp-for="FieldPlacementActivities"></select>
                                <span asp-validation-for="FieldPlacementActivities" class="text-danger"></span>
                            </div>
                            <div class="form-group pull-right">
                                <input type="submit" value="Create" class="btn bg-purple btn-block" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <a asp-action="UnitList">Back to List</a>
            </div>

        </div>
    </section>

src/FELTP.Web/Views/Unit/EditUnit.cshtml
@model UpdateUnitCommand
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Edit Topic</h4>
        </div>
        <div class="modal-body">
            <form action="/Unit/EditUnit" method="post" id="edit-unit-details-form">
                @Html.HiddenFor(x => x.Id)
                <div class="form-group">
                    <label asp-for="Code" class="control-label"></label>
                    <input asp-for="Code" class="form-control" />
                    <span asp-validation-for="Code" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label" style="display:inline">Has Activity</label>
                    <input class="checkbox" type="checkbox" asp-for="HasFieldPlacementActivity" />
                </div>
                @if (Model.HasFieldPlacementActivity)
                {
                    <div class="form-group" id="field-placement-activity-div">
                        <label class="control-label">Field Placement Activity</label>
                        <select class="form-control selectpicker" multiple asp-for="FieldPlacementActivityId"
                                asp-items="Model.FieldPlacementActivities"></select>
                        <span asp-validation-for="FieldPlacementActivityId" class="text-danger"></span>
                    </div>

                }

            </form>
        </div>
        <div class="modal-footer">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" id="btn-update-unit" class="btn bg-purple" value="Save" />
                </div>
            </div>
        </div>


    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/FELTP.Web/Views/Unit/UnitList.cshtml
@{
    ViewData["Title"] = "Topics";
}

@section Scripts
    {
    <script type="text/javascript" src="~/js/feltp/unit.js"></script>
    <script type="text/javascript" src="~/js/feltp/field-placement-activity-dropdown.js"></script>

}

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <section class="content-header">
                <ol class="breadcrumb pull-right">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="#">Topics List</a></li>
                </ol>
            </section>
            <h1 class="page-head-line">Topics List </h1>
        </div>
    </div>
    <div class="box box-header">
        <div class="box-body">
            <a asp-controller="Unit" asp-action="AddUnit" class="btn btn-default btn-md" style="margin-bottom:10px"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create New</a><p></p>
            <table id="units-list-table" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>
        </div>
    </div>
</section>

<div class="modal fade" id="units-details-modal" tabindex="-1" role="dialog" aria-labelledby="Edit Topic" aria-hidden="true" data-backdrop="static">
    <div id="units-details-container">
    </div>
</div>

src/FELTP.Web/Views/Unit/UnitResponse.cshtml
@model UpdateUnitResponse
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Topic Update Result</h4>
        </div>

        <div class="modal-body">
            <text class="success">
                @Model.Message
            </text>
        </div>
        <div class="modal-footer">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="button" class="btn btn-default"
                            data-url="@Url.Action("UnitList","Unit")" data-dismiss="modal" onclick="javascript:window.location.reload()">
                        Close
                    </button>
                </div>
            </div>
        </div>

    </div>
</div>

src/FELTP.Web/Views/Unit/ViewDetails.cshtml
@model UnitViewModel
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Topic Details</h4>
            </div>
            <div class="modal-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Code)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Code)
                    </dd>
                    <dt>
                        @Html.DisplayName("Created By")
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CreatedBy)
                    </dd>
                    <dt>
                        @Html.DisplayName("Date Created")
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.DateCreated)
                    </dd>
                    <dt>
                        @Html.DisplayName("Has Activity")
                    </dt>
                    <dd>
                        @Model.HasActivity.ToString()
                    </dd>
                </dl>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

src/FELTP.Web/Views/Unit/ViewUnitActivities.cshtml
@model UnitViewModel
<div class="modal-dialog" style="width:800px">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">@Model.Name Activities</h4>
        </div>
        <div class="modal-body">
            @Html.Hidden("UnitId",Model.Id)
            <table id="unit-activity-list-table" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>
        </div>
        <div class="modal-footer">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>