src/FELTP.Web/Controllers/EthicsManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.ResidentManagement.Commands;
using Application.ResidentManagement.Queries;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using FELTP.Web.Services;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using ResidentManagement.Domain.Ethics;
using UserManagement.Services.Authorization;

namespace FELTP.Web.Controllers
{
    public class EthicsManagementController : Controller
    {
        IEnumerable<ISelectListLoader> selectListLoader;
        ISelectListLoader programSelectListLoader;
        IMediator mediator;
        public EthicsManagementController(IEnumerable<ISelectListLoader> _selectListLoader, IMediator _mediator)
        {
            mediator = _mediator;
            selectListLoader = _selectListLoader;
            programSelectListLoader = selectListLoader.FirstOrDefault(x => x.CanLoad(SelectItemType.Program));
        }
        public IActionResult Index()
        {
            return View();
        }

        [Operation("Add Ethics Approval")]
        public async Task<IActionResult> EthicsApprovalForm()
        {
            var model = new AddEthicsApprovalCommand()
            {
                ProgramSelectList = await programSelectListLoader.GetSelectListAsync(null),

            };
            return View(model);
        }

        [HttpPost]
        [Operation("Add Ethics Approval")]
        public async Task<IActionResult> EthicsApprovalForm(AddEthicsApprovalCommand model, List<EthicsApprovalItemCommand> EthicsApprovalItems)
        {
            model.EthicsApprovalItems = EthicsApprovalItems;
            model.CreatedBy = User.Identity.Name;
            if (!ModelState.IsValid)
            {
                model.ProgramSelectList = await programSelectListLoader.GetSelectListAsync(null);
                return View(model);
            }

            var result = await mediator.Send(model);

            return RedirectToAction(nameof(EthicsApprovalList));
        }

        [Operation("Add Ethics Approval Committee")]      
        public async Task<IActionResult> EthicsApprovalCommitteePartial(long? residentDeliverableId)
        {

            var coAuthors = await mediator.Send(new GetResidentDeliverableCoauthors()
            {
                ResidentDeliverableId = residentDeliverableId
            });
            if (coAuthors.Any())
            {
                var ethicsCommitteeModel = coAuthors.Select(x => new EthicsApprovalItemCommand
                {
                    Author = x.AuthorName,
                    CommitteeName = x.CommitteeName,
                    CommitteeId = x.CommitteeId
                }).ToList();
                return PartialView(ethicsCommitteeModel);
            }

            var committees = await mediator.Send(new GetEthicsApprovalCommittee());
            var model = committees.Select(x => new EthicsApprovalItemCommand
            {
                CommitteeId = x.Id,
                CommitteeName = x.Name
            }).ToList();

            return PartialView(model);
        }

        [Operation("View Ethics Approval List")]
        public IActionResult EthicsApprovalList()
        {
            return View();
        }

        [Operation("View Ethics Approval List")]
        public async Task<IActionResult> GetEthicsApprovalList(IDataTablesRequest request)
        {
            var ethicsApprovals = await mediator.Send(new GetEthicsApprovalQuery());

            var filteredData = String.IsNullOrWhiteSpace(request.Search.Value)
                ? ethicsApprovals
                : ethicsApprovals.Where(_item => _item.ResidentName.Contains(request.Search.Value));

            var dataPage = filteredData.Skip(request.Start).Take(request.Length);

            var response = DataTablesResponse.Create(request, ethicsApprovals.Count(), filteredData.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }

        [Operation("View Ethics Approval Details")]
        public async Task<IActionResult> EthicsApprovalDetails(long Id)
        {
            var ethicsApproval = await mediator.Send(new GetEthicsApprovalQuery() { Id = Id });
            return View(ethicsApproval.SingleOrDefault());
        }

        public async Task<IActionResult> GetCommitteeByEthicsApprovalId(IDataTablesRequest request,
            long ethicsApprovalId)
        {
            var ethicsApprovalItems = await mediator.Send(new GetEthicsApprovalItems() { EthicsApprovalId = ethicsApprovalId });

            var distictCommitees = ethicsApprovalItems.GroupBy(x => x.CommitteeId)
                .Select(x => x.FirstOrDefault())
                .Select(x => new { x.Committee, x.CommitteeId, x.EthicsApprovalId, x.DateCreated });

            var filteredData = String.IsNullOrWhiteSpace(request.Search.Value)
                ? distictCommitees
                : distictCommitees.Where(_item => _item.Committee.Contains(request.Search.Value));

            var dataPage = filteredData.Skip(request.Start).Take(request.Length);

            var response = DataTablesResponse.Create(request, distictCommitees.Count(), filteredData.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }

        [Operation("View Ethics Approval Submissions")]
        public async Task<IActionResult> ViewEthicsApprovalSubmissions(long id, int committeeId)
        {
            var ethicsApproval = await mediator.Send(new GetEthicsApprovalQuery { Id = id });

            var committees = await mediator.Send(new GetEthicsApprovalCommittee { Id = committeeId });

            var submissionViewModel = new EthicsSubmissionViewModel
            {
                Committee = committees.SingleOrDefault().Name,
                CommitteeId = committeeId,
                DeliverableName = ethicsApproval.SingleOrDefault().DeliverableName,
                EthicsApprovalId = id,
                EventTypeId = ethicsApproval.SingleOrDefault().EventTypeId,
                SubmissionDueDate = ethicsApproval.SingleOrDefault().SubmissionDueDate,
                Title = ethicsApproval.SingleOrDefault().Title
            };

            return View(submissionViewModel);
        }

        [Operation("View Ethics Approval Committee Submissions")]
        public async Task<IActionResult> GetEthicsApprovalCommitteeSubmissions(IDataTablesRequest request, long id,
            int committeeId)
        {
            var ethicsApprovalItems = await mediator.Send(new GetEthicsApprovalItems() { EthicsApprovalId = id });

            ethicsApprovalItems = ethicsApprovalItems.Where(x => x.EthicsApprovalCommitteeId == committeeId).ToList();

            var filteredData = String.IsNullOrWhiteSpace(request.Search.Value)
                ? ethicsApprovalItems
                : ethicsApprovalItems.Where(_item => _item.Committee.Contains(request.Search.Value));

            var dataPage = filteredData.Skip(request.Start).Take(request.Length);

            var response = DataTablesResponse.Create(request, ethicsApprovalItems.Count(), filteredData.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }

        [Operation("Download Submission Document")]
        public async Task<IActionResult> DownloadSubmissionDocument(long id)
        {
            var documents = await mediator.Send(new GetEthicsApprovalDocumentQuery { Id = id });

            var doc = documents.SingleOrDefault();

            return File(doc.Document, doc.ContentType, doc.FileName);

        }

        [Operation("Evaluate Ethics Approval Submission")]
        public async Task<IActionResult> _EvaluateEthicsApprovalSubmission(long id)
        {
            var ethicsApprovalItem = await mediator.Send(new GetEthicsApprovalItems { EthicsApprovalItemId = id });

            var item = ethicsApprovalItem.SingleOrDefault();

            var model = new EvaluateEthicsApprovalSubmissionCommand()
            {
                ApprovalStatus = (EthicsApprovalStatus)Enum.Parse(typeof(EthicsApprovalStatus), item.ApprovalStatus),
                EthicsApprovalItemId = item.Id,
                EthicsApprovalCommitteeId = item.EthicsApprovalCommitteeId,
                EthicsApprovalId = item.EthicsApprovalId
            };
            return PartialView(model);
        }

        [HttpPost]
        [Operation("Evaluate Ethics Approval Submission")]
        public async Task<IActionResult> _EvaluateEthicsApprovalSubmission(EvaluateEthicsApprovalSubmissionCommand model)
        {
            if (!ModelState.IsValid)
                return PartialView(model);

            model.EvaluatedBy = User.Identity.Name;
            model.UpdatedBy = User.Identity.Name;

            var result = await mediator.Send(model);

            return RedirectToAction(nameof(ViewEthicsApprovalSubmissions),
                new { id = model.EthicsApprovalId, committeeId = model.EthicsApprovalCommitteeId });
        }

        [Operation("Override Ethics Approval Outcome")]
        public async Task<IActionResult> OverrideEthicsApprovalOutcome(long id)
        {
            var ethicsApproval = await mediator.Send(new GetEthicsApprovalQuery { Id = id });

            var approvalModel = ethicsApproval.SingleOrDefault();

            var ethicsApprovalOutcome = new OverrideEthicsApprovalOutcomeCommand
            {
                ApprovalStatus = (EthicsApprovalStatus)Enum.Parse(typeof(EthicsApprovalStatus), approvalModel.ApprovalStatus),
                Deliverable = approvalModel.DeliverableName,
                EthicsApprovalId = approvalModel.Id,
                EventTypeId = approvalModel.EventTypeId,
                Title = approvalModel.Title,
                Message = approvalModel.ApprovalStatus == EthicsApprovalStatus.Approved.ToString() ?
                "Ethics approval status is approved hence cannot be altered" : String.Empty
            };

src/FELTP.Web/Views/EthicsManagement/EthicsApprovalCommitteePartial.cshtml
@model List<EthicsApprovalItemCommand>
<table id="committee-approval-table" class="table"  cellspacing="0" width="100%">
    <tr>
        <th >
            Ethics Approval Committee
        </th>
        <th >
            CoAuthor Name
        </th>
        <th>
            Submission Date
        </th>
        <th >
            Approval Status
        </th>
        <th>
            Comment
        </th>
    </tr>


    @for (int com = 0; com < Model.Count(); com++)
    {
        string className = "show-approval-committee";
        if (com > 1)
        {
            className = "hide-approval-committee";

        }
        @Html.HiddenFor(x => x[com].CommitteeId)
        @Html.HiddenFor(x => x[com].CommitteeName)
        <tr>
            <td class="@className">
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="@Model[com].Selected" /> @Html.DisplayFor(model => model[com].CommitteeName)
                        </label>
                    </div>
                </div>
            </td>
            <td class="@className">
                <div class="form-group">
                    @if (String.IsNullOrEmpty(Model[com].Author))
                    {

                        <text>
                        Not Specified
                        </text>

                    }
                    else
                    {

                        @Html.DisplayFor(model => model[com].Author)
                    }

                </div>
            </td>
            <td class="@className">
                <div class="form-group">
                    <div class='input-group date date-submitted'>
                        <input type='text' class="form-control" asp-for="@Model[com].StrDateSubmitted" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <span asp-validation-for="@Model[com].StrDateSubmitted" class="text-danger"></span>
                </div>

            </td>
            <td class="@className">
                <div class="form-group">
                    <select asp-for="@Model[com].ApprovalStatus" asp-items="Html.GetEnumSelectList<ApprovalStatus>()"
                            class="form-control selectpicker">
                        <option value="0">Select Status</option>
                    </select>
                    <span asp-validation-for="@Model[com].ApprovalStatus" class="text-danger"></span>
                </div>
            </td>
            <td class="@className">
                <div class="form-group">
                    <input asp-for="@Model[com].Comment" class="form-control" />
                    <span asp-validation-for="@Model[com].Comment" class="text-danger"></span>
                </div>
            </td>
        </tr>
    }
</table>
<div id="toggle-approval-commitee-div" style="display:none">
    <a> <<< Show More</a>
</div>
<div id="hide-approval-commitee-div" style="display:none">
    <a> >>> Show Less</a>
</div>
<script>
    $(function () {
        $('.date-submitted').datetimepicker({
            format: 'DD/MM/YYYY'
        });
    });
</script>

src/FELTP.Web/Views/EthicsManagement/EthicsApprovalDetails.cshtml
@model EthicsApprovalViewModel

@{
    ViewData["Title"] = "Ethics Approval Details";
}

@section Scripts
    {
    <script src="~/js/feltp/ethics-management.js"></script>
}

<div class="row">
    <div class="col-md-12">
        <section class="content-header">
            <ol class="breadcrumb pull-right">
                <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                <li><a href="#">Ethics Approval Details</a></li>
            </ol>
        </section>
        <h1 class="page-head-line">  @ViewData["Title"]</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        <div class="box box-header">
            @Html.Hidden("EthicsApprovalId", Model.Id)
            <div class="col-md-12" style="padding-right:5px;padding-left:5px">
                @if (Model == null)
                {
                    <div>
                        Ethics Approval Details Not Found
                    </div>
                    return;

                }

                <div class="col-md-6">
                    <div class="col-md-6">
                        <b>Resident</b>
                    </div>
                    <div class="col-md-6">
                        @Model.ResidentName
                    </div>

                    <div class="col-md-6">
                        <b> Deliverable </b>
                    </div>
                    <div class="col-md-6">
                        @Model.DeliverableName
                    </div>

                    <div class="col-md-6">
                        <b>Date Created</b>
                    </div>
                    <div class="col-md-6">
                        @Model.DateCreated
                    </div>
                    <div class="col-md-6">
                        <b>Created By</b>
                    </div>
                    <div class="col-md-6">
                        @Model.CreatedBy
                    </div>

                </div>
                <div class="col-md-6">
                    <div class="col-md-6">
                        <b>Approval Status</b>
                    </div>
                    <div class="col-md-6">
                        @Model.ApprovalStatus
                    </div>
                    <div class="col-md-6">
                        <b>Event Type </b>
                    </div>
                    <div class="col-md-6">
                        @Model.EventTypeId
                    </div>
                    <div class="col-md-6">
                        <b>Event Title </b>
                    </div>
                    <div class="col-md-6">
                        @Model.Title
                    </div>
                    <div class="col-md-6">
                        <b>Submission Due Date </b>
                    </div>
                    <div class="col-md-6">
                        @Model.SubmissionDueDate
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="box box-header" style="height: 140px;">
            <div class="box-header with-border">
                <h3 class="box-title">Action Links</h3>
            </div>
            <div class="box-body">
                <a href="/EthicsManagement/OverrideEthicsApprovalOutcome?Id=@Model.Id&status=@Model.ApprovalStatus" class="override-ethics-approval-outcome btn btn-primary btn-md pull-left btn-sm">
                    Override Ethics Approval Outcome
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box box-header">
            <div class="box-header with-border">
                <h3 class="box-title">Ethics Approval Committees</h3>
            </div>
            <div class="box-body">
                <table id="ethics-approval-committee-table" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>

                <a asp-action="EthicsApprovalList" class="pull-right">Back to List</a>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="override-ethics-approval-submissions-modal" tabindex="-1" role="dialog" aria-labelledby="Override Ethics Approval Submission" aria-hidden="true" data-backdrop="static">
    <div id="override-ethics-approval-submissions-container">
    </div>
</div>

src/FELTP.Web/Views/EthicsManagement/EthicsApprovalForm.cshtml
@model AddEthicsApprovalCommand
@{
    ViewData["Title"] = "Ethics Approval Form";
}
@section Scripts
    {
    <script src="~/js/feltp/ethics-management.js"></script>
}

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <section class="content-header">
                <ol class="breadcrumb pull-right">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="/EthicsManagement/EthicsApprovalList">Ethics Approval List</a></li>
                    <li><a href="#">Ethics Approval Form</a></li>
                </ol>
            </section>
            <h1 class="page-head-line">Ethics Approval Form </h1>
        </div>
    </div>
    <div class="box box-header">
        <div class="box-body">
            <div class="row">
                <form asp-action="EthicsApprovalForm" enctype="multipart/form-data">
                    @Html.HiddenFor(x => x.StrSubmissionExpiryDate)
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Select Program</label>
                            <select asp-for="ProgramId" asp-items="@Model.ProgramSelectList" data-live-search="true"
                                    class="form-control selectpicker">
                                <option value="0">Select Program</option>
                            </select>
                            <span asp-validation-for="ProgramId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Select Program Offer </label>
                            <select class="form-control selectpicker" asp-for="ProgramOfferId"></select>
                            <span asp-validation-for="ProgramOfferId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Select Resident</label>
                            <select asp-for="ProgramEnrollmentId" class="form-control selectpicker" data-live-search="true"></select>
                            <span asp-validation-for="ProgramEnrollmentId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Select Deliverable</label>
                            <select asp-for="ResidentDeliverableId" class="form-control selectpicker" data-live-search="true">
                                <option value="0">Select Deliverable</option>
                            </select>
                            <span asp-validation-for="ResidentDeliverableId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Select Presentation Event</label>
                            <select asp-for="ProgramEventId" class="form-control selectpicker" data-live-search="true">
                                <option value="0">Select Event</option>
                            </select>
                            <span asp-validation-for="ProgramEventId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Select Paper Category</label>
                            <select asp-for="PaperCategory" asp-items="@Html.GetEnumSelectList<PaperCategory>()" class="form-control selectpicker">
                                <option value="0">
                                    Select Category
                                </option>
                            </select>
                            <span asp-validation-for="PaperCategory" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label"> Select Document Version </label>
                            <select asp-for="DocumentVersion" asp-items="@Html.GetEnumSelectList<DocumentVersion>()" class="form-control selectpicker">
                                <option value="0">
                                    Select Version
                                </option>
                            </select>
                            <span asp-validation-for="DocumentVersion" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label"> Upload Document </label>
                            <input type="file" asp-for="FormFile" class="form-control" />
                            <span asp-validation-for="FormFile" class="text-danger"></span>
                        </div>
                        <div class="form-group" id="submission-expiry-date-div" style="display:none">
                            <label class="control-label"> Submission Expiry Date </label>
                            <input asp-for="SubmissionExpiryDate" disabled="disabled" />
                        </div>
                    </div>
                    <div id="ethics-approval-committee-div" style="display:none">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-primary bg-purple margin pull-right" />
                            </div>
                        </div>
                    </div>
                </form>
                <div class="box-footer">
                    <a asp-action="EthicsApprovalList">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</section>

src/FELTP.Web/Views/EthicsManagement/EthicsApprovalList.cshtml
@{
    ViewData["Title"] = "Ethics Approval List";
}

@section Scripts
    {
    <script type="text/javascript" src="~/js/feltp/ethics-management.js"></script>
}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <section class="content-header">
                <ol class="breadcrumb pull-right">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="#"><u>Ethics Approval List</u></a></li>
                </ol>
            </section>
            <h1 class="page-head-line">Ethics Approval List </h1>
        </div>
    </div>
    <div class="box box-header">
        <div class="box-body">
            <a asp-controller="EthicsManagement" asp-action="EthicsApprovalForm" class="btn btn-default btn-md" style="margin-bottom:10px"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create New</a><p></p>
            <table id="ethics-approval-list-table" class="table table-bordered table-striped" cellspacing="0" width="100%"></table>
        </div>
    </div>
</section>

src/FELTP.Web/Views/EthicsManagement/OverrideEthicsApprovalOutcome.cshtml
@model OverrideEthicsApprovalOutcomeCommand

@{
    ViewData["Title"] = "Override Ethics Approval Outcome";
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Override Ethics Approval Outcome</h4>
        </div>
        <form asp-action="OverrideEthicsApprovalOutcome">
            <div class="modal-body">
                @Html.HiddenFor(x => x.Deliverable)
                @Html.HiddenFor(x => x.EthicsApprovalId)
                @Html.HiddenFor(x => x.EventTypeId)
                @Html.HiddenFor(x => x.Title)
                @if (Model.ApprovalStatus == EthicsApprovalStatus.Approved)
    {
            <text>
            @Model.Message
            </text>
return;
}

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col-md-6">
                        <b> Deliverable Name</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        @Html.DisplayFor(x => x.Deliverable)
                    </div>
                    <div class="col-md-6">
                        <b> Event Type</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">

                        @Html.DisplayFor(x => x.EventTypeId)
                    </div>
                    <div class="col-md-6">

                        <b> Title</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">
                        @Html.DisplayFor(x => x.Title)
                    </div>
                    <div class="col-md-6">
                        <b>Approval Status</b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">

                        <select asp-for="ApprovalStatus"
                                asp-items="@Html.GetEnumSelectList<ApprovalStatus>()" class="form-control selectpicker">
                            <option value="@Model.ApprovalStatus"></option>
                        </select>
                    </div>
                    <div class="col-md-6">
                        <b>OverrideReason </b>
                    </div>
                    <div class="col-md-6" style="margin-bottom:10px">

                        <input asp-for="OverrideReason" class="form-control" />
                        <span asp-validation-for="OverrideReason" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn bg-purple" value="Save" />
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
@section Scripts {


    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/FELTP.Web/Views/EthicsManagement/_EvaluateEthicsApprovalSubmission.cshtml
@model EvaluateEthicsApprovalSubmissionCommand

@{
    ViewData["Title"] = "Evaluate Ethics Approval Submission";
}

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Evaluate Ethics Approval Submission</h4>
            </div>
            <form asp-action="_EvaluateEthicsApprovalSubmission">
                <div class="modal-body">
                    @Html.HiddenFor(x => x.EthicsApprovalCommitteeId)
                    @Html.HiddenFor(x => x.EthicsApprovalItemId)
                    @Html.HiddenFor(x=>x.EthicsApprovalId)

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="ApprovalStatus" class="control-label">Approval Status</label>
                        <select asp-for="ApprovalStatus"
                                asp-items="@Html.GetEnumSelectList<EthicsApprovalStatus>()" class="form-control selectpicker">
                            <option value="@Model.ApprovalStatus"></option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Comment" class="control-label"></label>
                        <input asp-for="Comment" class="form-control" />
                        <span asp-validation-for="Comment" class="text-danger"></span>
                    </div>

                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <input type="submit" class="btn bg-purple" value="Save" />
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
@section Scripts {


    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}